name: multiply

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - gdal
  - shapely
  - setuptools
  - pyyaml
  - pdal
  - python-pdal
  - gdal
  - h5py
  - pyproj
  - xarray
  - sentinelhub
  - numpy
  - lxml
  - scipy
  - beautifulsoup4
  - pip:
    - git+https://github.com/QCDIS/multiply-core.git