name: multiply

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.9*
  #
  # runtime dependencies
  #
  - gdal = 3.4.0
#  - beautifulsoup4 = 4.11.1
#  - shapely = 1.8.0
#  - html5lib = 1.1
#  - pyyaml = 3.12
#  - requests = 2.28.0
#  - pytest =7.1.2
#  - mock = 4.0.3