name: multiply-data-access
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - gdal=3.0
  - libgdal
  - pyproj
  - pyyaml
  - numpy
  - scipy
  - setuptools
  - gcc=12.1.0
  - cxx-compiler
  - libgcc=5.2.0
  - lazrs-python
  - laspy
  - plyfile
  - beautifulsoup4
  - lxml
  - shapely
  - pyshp
  - pytest
  - xarray
  - netcdf4
  - h5netcdf
  - flake8
  - pip
  - pip:
      - .
      - git+https://github.com/QCDIS/multiply-core.git




