name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 3 * * *'
  workflow_call:
    inputs:
      days:
        required: false
        type: string
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '8 days'


