name: Sync with Original Repo
on:
  schedule:
  - cron:  "*/15 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream
      run: git merge upstream/main --no-edit

    - name: Push changes
      run: git push

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Sync with upstream"
        title: "Sync with upstream"
        branch: "sync"  # Update with the branch name you want to create the pull request from
        body: "This pull request syncs with the upstream repository."
