on:
  push:
    tags:
    - '*'

jobs:
  conda:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: multiply
          environment-file: environment.yaml
          python-version: 3.9
      - run: |
          python setup.py bdist_wheel
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}


      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/multiply_data_access-0.5.2-py3-none-any.whl"
          tag: ${{steps.tag.outputs.tag}}
          commit: main