on: [push]

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base && \
        $CONDA/bin/conda activate base

    - name: bdist_wheel
      run: |
        $CONDA/bin/conda activate base && \
        python setup.py bdist_wheel --universal
    - name: 'Upload wheel artifact'
      uses: actions/upload-artifact@v3
      with:
        name: multiply_data_access
        path: dist/multiply_data_access-0.5.2-py2.py3-none-any.whl